<?php

/**
 * @file
 * Lit SSR module file.
 */

/**
 * Implements hook_views_post_render().
 */
function lit_ssr_views_post_render(
  Drupal\views\ViewExecutable $view,
  array &$output,
  Drupal\views\Plugin\views\cache\CachePluginBase $cache
) {
  // The object must implement \Drupal\Core\Security\TrustedCallbackInterface.
  // $output['#post_render'][] = '\Drupal\lit_ssr\LitSsrService::ssr';
  $output['#post_render'][] = function($html) {
    $client = Drupal::httpClient();;
    $response = $client->request('POST', 'http://my_drupal10_project_ssr:3333', [
      'body' => $html,
      'headers' => [
        'Content-Type' => 'text/html',
        'Accept'     => 'text/html',
      ]
    ]);
    if ($response->getStatusCode() != 200) {
      return $html;
    }
    return $response->getBody()->getContents();
  };
}
